import type { Generated } from "kysely";

export interface UserTable {
  id: Generated<number>; // Kysely built-in type for auto-increment IDs
  /*
Generated<T> tells Kysely:
“This field is generated by the database (like AUTO_INCREMENT), so don’t expect it on insert sql query.” 
  */
  username: string;
  password: string;
}

export interface QuoteTable {
  id: Generated<number>;
  user_id: number;
  movie: string;
  quote: string;
}

// Here DB is our whole database schema/structure. It's a map that connects table names (users, quotes) to the shape of each table (UserTable, QuoteTable)
// We have passed this 'DB' into Kysely in 'client.ts' (look there) which makes 'db' fully typed and safe.
export interface DB {
  users: UserTable;
  quotes: QuoteTable;
}

// We use interface for defining the schema because Kysely supports (and expects) interface-based schema definitions.
